# This workflow will install the dependencies, run tests and lint every push

name: Build Java

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: ['8']
    name: Java ${{ matrix.java }}
    steps:
      - uses: actions/checkout@v2
      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Run tests
        run: mvn clean formatter:validate test integration-test verify -DappId=${{ secrets.APP_ID }} -Dcluster=${{ secrets.CLUSTER_URL }} -DappKey=${{ secrets.APP_KEY }} -Dauthority=${{ secrets.TENANT_ID }} -Ddatabase=${{ secrets.DATABASE_NAME }} -Dlog4j2.configurationFile=/home/ram/workspace/flink-connector-kusto/connector-core/src/test/resources/log4j2.properties
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            connector-core/target/failsafe-reports/TEST*.xml
            connector-core/target/surefire-reports/TEST*.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2