# This workflow will install the dependencies, run tests and lint every push

name: Build Java

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ '**' ]
jobs:
  build:
    runs-on: ubuntu-latest
    environment: build
    permissions:
      contents: read
      issues: read
      checks: write
      pull-requests: write
      id-token: write
    strategy:
      matrix:
        java: ['8']
    name: Java ${{ matrix.java }}
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.APP_ID }}
          tenant-id: ${{ secrets.AUTH_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}
      - uses: actions/checkout@v2
      - name: Setup java ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: ${{ matrix.java }}
          cache: 'maven'
      - name: Run tests
        run: mvn clean compile test-compile formatter:validate test integration-test verify -Dcluster=${{ secrets.CLUSTER_URL }} -Ddatabase=${{ secrets.DATABASE_NAME }} -U -am
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            connector-core/target/failsafe-reports/TEST*.xml
            connector-core/target/surefire-reports/TEST*.xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3